# (3) RANDOM FOREST CLASSIFICATION

### Importing needed libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

### Reading the Data

In [2]:
df=pd.read_csv("bill_authentication.csv")
df.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

### Preparing the Data for Train/Test Split

The following code divides the dataset into attributes/features and class/labels

In [4]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values
print(X[0:5])
print()
print(y[0:5])

#(OR)
#feature = df[['Variance','Skewness','Curtosis','Entropy']]
#X = np.array(feature)
#X[0:5]

#y=np.array(df['Class'])
#y[0:5]

[[ 3.6216   8.6661  -2.8073  -0.44699]
 [ 4.5459   8.1674  -2.4586  -1.4621 ]
 [ 3.866   -2.6383   1.9242   0.10645]
 [ 3.4566   9.5228  -4.0112  -3.5944 ]
 [ 0.32924 -4.4552   4.5718  -0.9888 ]]

[0 0 0 0 0]


### Train/Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.2, random_state=0)
print('Train Set: ', X_train.shape, y_train.shape)
print('Test Set: ', X_test.shape, y_test.shape)

Train Set:  (1097, 4) (1097,)
Test Set:  (275, 4) (275,)


### Normalization of Data

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Modeling 

**n_estimators: int, default=100 :**
The number of decision trees in the random forest.

**max_features: {“auto”, “sqrt”, “log2”}, int or float, default=”auto” :**
The number of features/columns to consider when looking for the best split at each node.

**bootstrap: bool, default=True :**
Whether bootstrap samples are used when building trees. If False, the whole dataset is used to build each tree.

**random_state: int or RandomState, default=None**
Controls both the randomness of the bootstrapping of the samples used when building trees (if bootstrap=True) and the sampling of the features to consider when looking for the best split at each node (if max_features < n_features).

In [21]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, bootstrap=True)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=20, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

### Predicting

In [22]:
y_pred = regressor.predict(X_test).astype(int)
y_pred[0:5]

array([1, 0, 1, 0, 0])

### Evaluation

In [23]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import jaccard_similarity_score

print('Confusion Matrix: ',confusion_matrix(y_test,y_pred))
print('\nClassification Report: ',classification_report(y_test,y_pred))
print('\nAccuracy Score:',accuracy_score(y_test, y_pred))
print('\nJaccard Similarity Score: ',jaccard_similarity_score(y_test,y_pred))

Confusion Matrix:  [[157   0]
 [ 11 107]]

Classification Report:                precision    recall  f1-score   support

           0       0.93      1.00      0.97       157
           1       1.00      0.91      0.95       118

    accuracy                           0.96       275
   macro avg       0.97      0.95      0.96       275
weighted avg       0.96      0.96      0.96       275


Accuracy Score: 0.96

Jaccard Similarity Score:  0.96


c:\users\anann\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\metrics\_classification.py:656: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  warnings.warn('jaccard_similarity_score has been deprecated and replaced '
